In [1]:
import torch
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms

# Writer will output to ./runs/ directory by default
writer = SummaryWriter()

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
trainset = datasets.MNIST('mnist_train', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
model = torchvision.models.resnet50(False)
# Have ResNet model take in grayscale rather than RGB
model.conv1 = torch.nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
images, labels = next(iter(trainloader))

grid = torchvision.utils.make_grid(images)
writer.add_image('images', grid, 0)
writer.add_graph(model, images)
writer.close()

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [2]:
from torch.utils.tensorboard import SummaryWriter
import numpy as np
import os
writer = SummaryWriter()

for n_iter in range(100):
    t= os.path.join('Loss','cane')
    writer.add_scalar(t, np.random.random(), n_iter)
    writer.add_scalar('Loss/test', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/train', np.random.random(), n_iter)
    writer.add_scalar('Accuracy/test', np.random.random(), n_iter)

In [3]:
print('mi'.join('l'))

l


In [3]:
import numpy as np

res_32 = np.array([])
res_64 = np.array([])
res_128 = np.array([])
res_256 = np.array([])
res_loss = np.array([])
log_loss_dict = {'low':res_256,'medium':res_128,'high':res_64,'huge':res_32,'loss':res_loss}

In [15]:
log_vars = {'low':8,'medium':2,'high':3,'huge':4,'loss':5}

for log_var in log_vars:
    log = log_vars[log_var]
    print('log',log_var,'is : ',log)
    print(log_loss_dict)
    log_loss_dict[log_var] = np.append(log_loss_dict[log_var],log)

log low is :  8
{'low': array([1., 1., 4., 8., 8., 8., 8.]), 'medium': array([2., 2., 2., 2., 2., 2., 2.]), 'high': array([3., 3., 3., 3., 3., 3., 3.]), 'huge': array([4., 4., 4., 4., 4., 4., 4.]), 'loss': array([5., 5., 5., 5., 5., 5., 5.])}
log medium is :  2
{'low': array([1., 1., 4., 8., 8., 8., 8., 8.]), 'medium': array([2., 2., 2., 2., 2., 2., 2.]), 'high': array([3., 3., 3., 3., 3., 3., 3.]), 'huge': array([4., 4., 4., 4., 4., 4., 4.]), 'loss': array([5., 5., 5., 5., 5., 5., 5.])}
log high is :  3
{'low': array([1., 1., 4., 8., 8., 8., 8., 8.]), 'medium': array([2., 2., 2., 2., 2., 2., 2., 2.]), 'high': array([3., 3., 3., 3., 3., 3., 3.]), 'huge': array([4., 4., 4., 4., 4., 4., 4.]), 'loss': array([5., 5., 5., 5., 5., 5., 5.])}
log huge is :  4
{'low': array([1., 1., 4., 8., 8., 8., 8., 8.]), 'medium': array([2., 2., 2., 2., 2., 2., 2., 2.]), 'high': array([3., 3., 3., 3., 3., 3., 3., 3.]), 'huge': array([4., 4., 4., 4., 4., 4., 4.]), 'loss': array([5., 5., 5., 5., 5., 5., 5.])}

In [ ]:
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/MODEL_1_TRAINING{}'.format(timestamp))

In [16]:


for log in log_loss_dict:
    print('log ', log)
    print(log_loss_dict[log])
    mean = np.mean(log_loss_dict[log])
    print('mean for ', log , 'is ',mean)
    t= os.path.join('Loss',str(log))
    writer.add_scalar(t,mean,1)


log  low
[1. 1. 4. 8. 8. 8. 8. 8.]
mean for  low is  5.75
log  medium
[2. 2. 2. 2. 2. 2. 2. 2.]
mean for  medium is  2.0
log  high
[3. 3. 3. 3. 3. 3. 3. 3.]
mean for  high is  3.0
log  huge
[4. 4. 4. 4. 4. 4. 4. 4.]
mean for  huge is  4.0
log  loss
[5. 5. 5. 5. 5. 5. 5. 5.]
mean for  loss is  5.0
